// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb11wKXmaVtvsqBYZD3Gb5ZT_1HXKC748',
    appId: '1:229530234889:web:6f67196bab0294dfcc08d8',
    messagingSenderId: '229530234889',
    projectId: 'nutmember-18c49',
    authDomain: 'nutmember-18c49.firebaseapp.com',
    storageBucket: 'nutmember-18c49.appspot.com',
    measurementId: 'G-Z0RVLFFKQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCASI07GHic6IgKHzfoo_MffsAi_yLaYkc',
    appId: '1:229530234889:android:13d632aca74daf00cc08d8',
    messagingSenderId: '229530234889',
    projectId: 'nutmember-18c49',
    storageBucket: 'nutmember-18c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDOrV8CLbxVZXkBWqc2v4QNzzLHNf-5i4',
    appId: '1:229530234889:ios:63ba54e34b80fc6fcc08d8',
    messagingSenderId: '229530234889',
    projectId: 'nutmember-18c49',
    storageBucket: 'nutmember-18c49.appspot.com',
    iosBundleId: 'com.example.nutmember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDOrV8CLbxVZXkBWqc2v4QNzzLHNf-5i4',
    appId: '1:229530234889:ios:62d3756edea8eff4cc08d8',
    messagingSenderId: '229530234889',
    projectId: 'nutmember-18c49',
    storageBucket: 'nutmember-18c49.appspot.com',
    iosBundleId: 'com.example.nutmember.RunnerTests',
  );
}
